app1/urls.py
from rest_framework import routers
from rest_framework.authtoken.views import obtain_auth_token

from app1.views import IndexFuncionarioTemplateView, FuncionarioListView, FuncionarioUpdateView, \
    FuncionarioDeleteView, IndexClienteTemplateView, ClienteCreateView, ClienteListView, ClienteUpdateView, \
    ClienteDeleteView, IndexFornecedorTemplateView, FornecedorCreateView, FornecedorListView, FornecedorUpdateView, \
    FornecedorDeleteView, IndexProdutoTemplateView, ProdutoCreateView, ProdutoListView, ProdutoUpdateView, \
    ProdutoDeleteView, ProdutoFuncionarioListView, IndexOrcamentoTemplateView, OrcamentoCreateView, \
    OrcamentoListView, OrcamentoUpdateView, OrcamentoDeleteView, IndexMetaTemplateView, MetaCreateView, MetaListView, \
    MetaUpdateView, MetaDeleteView
from django.urls import path, include

from . import views



router = routers.DefaultRouter()
router.register(r"events", views.EventViewSet)
router.register(r"comments", views.CommentViewSet)

app_name = 'app1'

urlpatterns = [
    path('login', views.loginn, name='login'),
    path('logout', views.logoutt, name='logout'),
    path('indexx', views.indexx, name='indexx'),
    path('manutencao', views.manutencao, name='manutencao'),
    path('funcionario/cadastrar/', views.funcionario, name="cadastra_funcionario"),
    path("api-token-auth/", obtain_auth_token, name="api_token_auth"),
    path("api/v1/", include(router.urls)),
    path("agenda", views.agenda, name="agenda-events"),
    path("all", views.all, name="agenda-events-all"),
    path("<int:id>", views.show, name="agenda-events-show"),
    path("<int:year>/<int:month>/<int:day>", views.day, name="agenda-events-day"),
    path("new", views.new, name="agenda-events-new"),
    path("delete/<int:id>", views.delete, name="agenda-events-delete"),
    path("edit", views.edit, name="agenda-events-edit"),



    # GET /
    path('principalfuncionario/', IndexFuncionarioTemplateView.as_view(), name="principalfuncionario"),

    # GET /funcionarios
    path('funcionarios/', FuncionarioListView.as_view(), name="lista_funcionarios"),

    # GET/POST /funcionario/{pk}
    path('funcionario/<pk>', FuncionarioUpdateView.as_view(), name="atualiza_funcionario"),

    # GET/POST /funcionarios/excluir/{pk}
    path('funcionario/excluir/<pk>', FuncionarioDeleteView.as_view(), name="deleta_funcionario"),

######################################################################################################

    # GET /
    path('principalcliente/', IndexClienteTemplateView.as_view(), name="principalcliente"),

    # GET /cliente/cadastrar
    path('cliente/cadastrar', ClienteCreateView.as_view(), name="cadastra_cliente"),

    # GET /clientes
    path('clientes/', ClienteListView.as_view(), name="lista_clientes"),

    # GET/POST /cliente/{pk}
    path('cliente/<pk>', ClienteUpdateView.as_view(), name="atualiza_cliente"),

    # GET/POST /cliente/excluir/{pk}
    path('cliente/excluir/<pk>', ClienteDeleteView.as_view(), name="deleta_cliente"),

######################################################################################################

    # GET /
    path('principal/fornecedor/', IndexFornecedorTemplateView.as_view(), name="principalfornecedor"),

    # GET /forncedor/cadastrar
    path('fornecedor/cadastrar', FornecedorCreateView.as_view(), name="cadastra_fornecedor"),

    # GET /fornecedores
    path('fornecedores/', FornecedorListView.as_view(), name="lista_fornecedores"),

    # GET/POST /fornecedor/{pk}
    path('fornecedor/<pk>', FornecedorUpdateView.as_view(), name="atualiza_fornecedor"),

    # GET/POST /fornecedor/excluir/{pk}
    path('fornecedor/excluir/<pk>', FornecedorDeleteView.as_view(), name="deleta_fornecedor"),

######################################################################################################

    # GET /
    path('principal/fornecedor/', IndexProdutoTemplateView.as_view(), name="principalproduto"),

    # GET /produto/cadastrar
    path('produto/cadastrar/', ProdutoCreateView.as_view(), name="cadastra_produto"),

    # GET /produtos
    path('produtos/', ProdutoListView.as_view(), name="lista_produtos"),

# GET /produtos
    path('produtos/funcionario/', ProdutoFuncionarioListView.as_view(), name="lista_produtos_funcionario"),

    # GET/POST /produto/{pk}
    path('produto/<pk>', ProdutoUpdateView.as_view(), name="atualiza_produto"),

    # GET/POST /produto/excluir/{pk}
    path('produto/excluir/<pk>', ProdutoDeleteView.as_view(), name="deleta_produto"),

######################################################################################################
######################################################################################################

    # GET /
    path('principal/orcamento/', IndexOrcamentoTemplateView.as_view(), name="principalorcamento"),

    # GET /orcamento/cadastrar
    path('orcamento/cadastrar/', OrcamentoCreateView.as_view(), name="cadastra_orcamento"),

    # GET /orcamentos
    path('orcamentos/', OrcamentoListView.as_view(), name="lista_orcamentos"),

    # GET/POST /orcamento/{pk}
    path('orcamento/<pk>', OrcamentoUpdateView.as_view(), name="atualiza_orcamento"),

    # GET/POST /orcamento/excluir/{pk}
    path('orcamento/excluir/<pk>', OrcamentoDeleteView.as_view(), name="deleta_orcamento"),

######################################################################################################

######################################################################################################

    # GET /
    path('principal/meta/', IndexMetaTemplateView.as_view(), name="principalmeta"),

    # GET /meta/cadastrar
    path('meta/cadastrar/', MetaCreateView.as_view(), name="cadastra_meta"),

    # GET /metas
    path('metas/', MetaListView.as_view(), name="lista_metas"),

    # GET/POST /meta/{pk}
    path('meta/<pk>', MetaUpdateView.as_view(), name="atualiza_meta"),

    # GET/POST /meta/excluir/{pk}
    path('meta/excluir/<pk>', MetaDeleteView.as_view(), name="deleta_meta"),


]

security/urls.py
from django.contrib import admin
from django.urls.conf import include
from django.urls import path
from app1 import views


urlpatterns = [
    path('', views.loginn, name="login"),
    path('app1/', include('app1.urls')),
    path('admin/', admin.site.urls, name="admin"),
]

app1/views.py
from datetime import datetime, timedelta

from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from django.core.paginator import Paginator, InvalidPage
from django.http import HttpResponseRedirect, HttpResponse
from django.shortcuts import get_object_or_404, redirect, render
from django.urls import reverse
from django.urls import reverse_lazy
from django.utils.timezone import localdate
from django.views.defaults import bad_request, server_error
from django.views.generic import TemplateView, ListView, UpdateView, CreateView, DeleteView
from rest_framework import filters, viewsets
from rest_framework.permissions import IsAuthenticated


from app1.forms import FormCliente, FormFuncionario, FormFornecedor, FormProduto, EventForm, CommentForm, FormOrcamento, \
    FormMeta
from app1.models import Funcionario, Cliente, Fornecedor, Produto, Event, Comment, Orcamento, Metas
from .serializers import CommentSerializer, EventSerializer
from .services import split_str_date

ITEMS_PER_PAGE = 5
FIRST_PAGE = 1


# PÁGINA PRINCIPAL INDEX
# ----------------------------------------------
def indexx(request):
    return render(request, 'app3/index.html')

# PÁGINA PRINCIPAL MANUTENÇÃO
# ----------------------------------------------
def manutencao(request):
    return render(request, 'app3/manutencao.html')

# PÁGINA PRINCIPAL LOGIN
# ----------------------------------------------
def loginn(request):
    if request.method == 'POST':
        usuario = request.POST.get('usuario')
        senha = request.POST.get('senha')
        user = authenticate(username=usuario, password=senha)

        if user:
            if user.is_active:
                login(request, user)
                return HttpResponseRedirect(reverse('app1:indexx'))
            else:
                return HttpResponse("Sua Conta Não Esta Ativa.")
        else:
            print("Alguém Tentou Fazer Login e Falhou")
            print("Foi Usado userName: {} e senha: {}".format(usuario, senha))
            return HttpResponse("O Login ou Senha Está Incorreto.")

    else:
        return render(request, 'app3/login.html', {})

# PÁGINA PRINCIPAL LOGOUT
# ----------------------------------------------
@login_required
def logoutt(request):
    logout(request)
    return HttpResponseRedirect(reverse('login'))

# PÁGINA CADASTRO FUNCIONARIO
# ----------------------------------------------
def funcionario(request):
    if request.method == 'POST':
        form = FormFuncionario(request.POST)
        if form.is_valid():
            usuario = User()
            usuario.first_name = form.cleaned_data['first_name']
            usuario.last_name = form.cleaned_data['last_name']
            usuario.email = form.cleaned_data['email']
            usuario.username = form.cleaned_data['username']
            usuario.password = form.cleaned_data['password']

            usuario.save()
            usuario.set_password(usuario.password)
            usuario.save()

            func = Funcionario()
            func.CPF = form.cleaned_data['CPF']
            func.nascimento = form.cleaned_data['nascimento']
            func.telefone = form.cleaned_data['telefone']
            func.endereco = form.cleaned_data['endereco']
            func.CTPS = form.cleaned_data['CTPS']
            func.cargo = form.cleaned_data['cargo']

            func.usuario = usuario
            func.save()
            return HttpResponseRedirect(reverse('app1:lista_funcionarios'))
    else:
        form = FormFuncionario()

    return render(request, 'app3/funcionario/cadastra.html', {'form': form,})

# PÁGINA PRINCIPAL FUNCIONARIO
# ----------------------------------------------

class IndexFuncionarioTemplateView(TemplateView):
    template_name = "app3/funcionario/principal.html"

# LISTA DE FUNCIONÁRIOS
# ----------------------------------------------

class FuncionarioListView(ListView):
    template_name = "app3/funcionario/lista.html"
    model = Funcionario
    context_object_name = "funcionarios"


# ATUALIZAÇÃO DE FUNCIONÁRIOS
# ----------------------------------------------

class FuncionarioUpdateView(UpdateView):
    template_name = "app3/funcionario/atualiza.html"
    model = Funcionario
    fields = '__all__'
    context_object_name = 'funcionario'
    success_url = reverse_lazy("app1:lista_funcionarios")


# EXCLUSÃO DE FUNCIONÁRIOS
# ----------------------------------------------

class FuncionarioDeleteView(DeleteView):
    template_name = "app3/funcionario/exclui.html"
    model = Funcionario
    context_object_name = 'funcionario'
    success_url = reverse_lazy("app1:lista_funcionarios")

##################################################################################

# PÁGINA PRINCIPAL CLIENTE
# ----------------------------------------------

class IndexClienteTemplateView(TemplateView):
    template_name = "app3/cliente/principal.html"

# LISTA DE CLIENTE
# ----------------------------------------------

class ClienteListView(ListView):
    template_name = "app3/cliente/lista.html"
    model = Cliente
    context_object_name = "clientes"

# CADASTRAMENTO DE CLIENTE
# ----------------------------------------------

class ClienteCreateView(CreateView):
    template_name = "app3/cliente/cadastra.html"
    model = Cliente
    form_class = FormCliente
    success_url = reverse_lazy("app1:lista_clientes")

# ATUALIZAÇÃO DE CLIENTE
# ----------------------------------------------

class ClienteUpdateView(UpdateView):
    template_name = "app3/cliente/atualiza.html"
    model = Cliente
    fields = '__all__'
    context_object_name = 'cliente'
    success_url = reverse_lazy("app1:lista_clientes")


# EXCLUSÃO DE CLIENTE
# ----------------------------------------------

class ClienteDeleteView(DeleteView):
    template_name = "app3/cliente/exclui.html"
    model = Cliente
    context_object_name = 'cliente'
    success_url = reverse_lazy("app1:lista_clientes")

##################################################################################

# PÁGINA PRINCIPAL FORNECEDOR
# ----------------------------------------------

class IndexFornecedorTemplateView(TemplateView):
    template_name = "app3/fornecedor/principal.html"

# LISTA DE FORNECEDOR
# ----------------------------------------------

class FornecedorListView(ListView):
    template_name = "app3/fornecedor/lista.html"
    model = Fornecedor
    context_object_name = "fornecedores"

# CADASTRAMENTO DE FORNECEDOR
# ----------------------------------------------

class FornecedorCreateView(CreateView):
    template_name = "app3/fornecedor/cadastra.html"
    model = Fornecedor
    form_class = FormFornecedor
    success_url = reverse_lazy("app1:lista_fornecedores")

# ATUALIZAÇÃO DE FORNECEDOR
# ----------------------------------------------

class FornecedorUpdateView(UpdateView):
    template_name = "app3/fornecedor/atualiza.html"
    model = Fornecedor
    fields = '__all__'
    context_object_name = 'fornecedor'
    success_url = reverse_lazy("app1:lista_fornecedores")


# EXCLUSÃO DE FORNECEDOR
# ----------------------------------------------

class FornecedorDeleteView(DeleteView):
    template_name = "app3/fornecedor/exclui.html"
    model = Fornecedor
    context_object_name = 'fornecedor'
    success_url = reverse_lazy("app1:lista_fornecedores")

##################################################################################

# LISTA DE PRODUTO
# ----------------------------------------------

class ProdutoFuncionarioListView(ListView):
    template_name = "app3/produto/listafuncionario.html"
    model = Produto
    context_object_name = "produtos"

# PÁGINA PRINCIPAL PRODUTO
# ----------------------------------------------

class IndexProdutoTemplateView(TemplateView):
    template_name = "app3/fornecedor/principal.html"

# LISTA DE PRODUTO
# ----------------------------------------------

class ProdutoListView(ListView):
    template_name = "app3/produto/lista.html"
    model = Produto
    context_object_name = "produtos"

# CADASTRAMENTO DE PRODUTO
# ----------------------------------------------

class ProdutoCreateView(CreateView):
    template_name = "app3/produto/cadastra.html"
    model = Produto
    form_class = FormProduto
    success_url = reverse_lazy("app1:lista_produtos")

# ATUALIZAÇÃO DE PRODUTO
# ----------------------------------------------

class ProdutoUpdateView(UpdateView):
    template_name = "app3/produto/atualiza.html"
    model = Produto
    fields = '__all__'
    context_object_name = 'produto'
    success_url = reverse_lazy("app1:lista_produtos")


# EXCLUSÃO DE PRODUTO
# ----------------------------------------------

class ProdutoDeleteView(DeleteView):
    template_name = "app3/produto/exclui.html"
    model = Produto
    context_object_name = 'produto'
    success_url = reverse_lazy("app1:lista_produtos")

##################################################################################

# Create your views here.
class EventViewSet(viewsets.ModelViewSet):
    """
    Disponibiliza os eventos da agenda como uma API REST.
    """

    queryset = Event.objects.all()
    serializer_class = EventSerializer

    permission_classes = (IsAuthenticated,)


class CommentViewSet(viewsets.ModelViewSet):
    """
    Disponibiliza os eventos da agenda como uma API REST.
    """

    queryset = Comment.objects.all()
    serializer_class = CommentSerializer
    filter_backends = (filters.SearchFilter,)
    search_fields = ("event__id",)

    permission_classes = (IsAuthenticated,)

# PÁGINA PRINCIPAL AGENDA
# ----------------------------------------------
@login_required
def agenda(request):
    """
    Exibe a página principal da aplicaão.
    """
    context = {
        "hide_new_button": True,
        "priorities": Event.priorities_list,
        "today": localdate(),
    }

    return render(request, "app3/agenda/agenda.html", context)


@login_required
def all(request):
    """

app1/templates/app3/agenda/agenda.html
<!-- Tela Principal da Agenda -->
{% extends "app3/_layouts/base.html" %}{% load static %}
{% block conteudo %}

    <main role="main">
      <div class="jumbotron rounded-0 text-center div-background">
        <h1 class="display-5">Agenda de Serviços</h1>
      </div>
      <div class="container text-center">
        <div class="row">
          <div class="col-4 col-md-2 offset-md-3">
            <a href="#" data-toggle="modal" data-target="#addEvent">
              <img src="{% static 'app2/imgs/new.png' %}" class="img-fluid" alt=""/>
            </a>
            <br/>
            <h6 class="py-2">Novo Agendamento</h6>
          </div>
          <div class="col-4 col-md-2">
            <a href="{% url 'app1:agenda-events-day' today.year today.month today.day %}">
              <img src="{% static 'app2/imgs/today.png' %}" class="img-fluid" alt=""/>
            </a>
            <br/>
            <h6 class="py-2">Agenda de Hoje</h6>
          </div>
          <div class="col-4 col-md-2">
            <a href="{% url 'app1:agenda-events-all' %}">
              <img src="{% static 'app2/imgs/all.png' %}" class="img-fluid" alt=""/>
            </a>
            <br/>
            <h6 class="py-2">Todos os Agendamentos</h6>
          </div>
        </div>
      </div>
    </main>
{% include "app3/agenda/modals/new.html" %}
{% endblock %}

app1/templates/app3/agenda/day.html
<!-- Agendamentos do Dia -->
{% extends "app3/_layouts/base.html" %}{% load static %}
{% block conteudo %}
<body style="line-height: 0.5;">
    <main role="main">
      <div class="card">
        <div class="card-header d-flex justify-content-between">
          <div class="align-self-center">
            <a href="{% url 'app1:agenda-events-day' previous.year previous.month previous.day %}">&lt;&lt;</a>
          </div>
          <div class="align-self-center text-center">
            <strong>{{ day|date:"l" }}</strong>
  		        <h1 class="display-5">{{ day.day }}</h1>
              {{ day|date:"d/m/Y" }}
            </div>
            <div class="align-self-center mt-2 mb-5">
              <a href="{% url 'app1:agenda-events-day' next.year next.month next.day %}">&gt;&gt;</a>
            </div>
          </div>
          <div class="card-body">
              {% if events|length > 0 %}
              {% for event in events %}
            <div role="alert" class="d-flex alert {% if event.priority == '1' %} alert-success{% elif event.priority == '2' %} alert-warning{% elif event.priority == '3' %} alert-danger{% else %} alert-secondary{% endif %}">
              <div class="p-2 text-truncate">
                <a class="text-dark edit-event" id="event-{{ event.id }}-{{ event.priority }}" href="#">{{ event.event }}</a>
              </div>
              <div class="p-2">
                <span class="badge badge-pill badge-dark">
                  <a href="{% url 'app1:agenda-events-show' event.id %}" class="text-white mb-2">
                  {% if event.number_of_comments > 0 %}
                    {{ event.number_of_comments }} comentário{{ event.number_of_comments|pluralize }}
                  {% else %}
                    Comentar!
                  {% endif %}
                  </a>
                </span>
                </div>
                <div class="p-2  ml-auto">
                  <a class="alert-link" href="{% url 'app1:agenda-events-delete' event.id %}"><span class="oi oi-pencil">&times;</span></a>
                </div>
              </div>
           {% endfor %}
          {% else %}
            <div class="alert alert-secondary text-center">
              Sem agendamento para este dia.
            </div>
          {% endif %}
          </div>
        </div>
    </main>
</body>
{% include "app3/agenda/modals/new.html" %}
{% include "app3/agenda/modals/edit.html" %}
{% endblock %}

app1/templates/app3/agenda/dead_index.html
{% extends "app3/_layouts/base.html" %}{% load static %}
{% block conteudo %}

    <body>

        <style>
#searchResults{
    display:none;
    position:absolute;
    z-index:1;
    width:100%;
    /* top:0; */
    background-color:rgba(255, 255, 255, 0.75);
}
        </style>
        <main role="main">
            <div class="jumbotron rounded-0 text-center div-background">
                <h1 class="display-5">Agenda de Serviços</h1>
            </div>
            <div class="container text-center">
                <div class="row">
                    <div class="col-md-6 offset-md-3">
                        <label for="searchEvents"></label><input id="searchEvents" type="text" class="form-control  text-center" name="search" placeholder="Buscar em eventos...">
                        <br/>
                    </div>
                </div>
                <div class="row">
                    <div id="searchResults" class="col-md-6 offset-md-2">
                        as
                        </div>
                    </div>
                </div>
                <div class="row" style="z-index:1;">
                    <div class="col-4 col-md-2 offset-md-3">
                        <a href="#" data-toggle="modal" data-target="#addEvent"><img src="{% static 'app2/imgs/new.png' %}" class="img-fluid" alt=""/></a><br/>
                        <h6 class="py-2">Novo Agendamento</h6>
                    </div>
                    <div class="col-4 col-md-2">
                        <a href="{% url 'app1:agenda-events-day' today.year today.month today.day %}"><img src="{% static 'app2/imgs/today.png' %}" class="img-fluid" alt=""/></a><br/>
                        <h6 class="py-2">Agenda de Hoje</h6>
                    </div>
                    <div class="col-4 col-md-2">
                        <a href="{% url 'app1:agenda-events-all' %}"><img src="{% static 'app2/imgs/all.png' %}" class="img-fluid" alt=""/></a><br/>
                        <h6 class="py-2">Todos os Agendamentos</h6>
                    </div>
                </div>
            </div>
        </main>
        <!-- offset-md-3 -->

<script>
$('#searchEvents').keypress(function(event){

    let dataToSearch = this.value
    let keyTrigger = event.charCode === 32

    if (dataToSearch.length === 0) {
        $('#searchResults').empty()
        $('#searchResults').hide()
    }

    if (keyTrigger || dataToSearch.length > 2){

        $('#searchResults').append("<div>pi</div>")
        $('#searchResults').show()

    }


})
</script>
    </body>
{% endblock %}
<!--
    vim: tabstop=8 expandtab shiftwidth=4 softtabstop=4
-->

app1/templates/app3/agenda/events.html
<!-- Todos os agendamentos -->
{% extends "app3/_layouts/base.html" %}{% load static %}
{% block conteudo %}

    <main role="main">
      <div class="card">
        <div class="card-header d-flex justify-content-between">
          <h1>Agenda de Serviços</h1>
        </div>
        <div class="card-body">
        {% if events|length > 0 %}
          <table class="table table-sm table-responsive-sm">
            <thead class="thead-dark">
              <tr>
                <th>Data</th><th>Serviço</th>
              </tr>
            </thead>
            <tbody>
            {% for event in events %}
              <tr class="{% if event.priority == '1' %} table-success{% elif event.priority == '2' %} table-warning{% elif event.priority == '3' %} table-danger{% else %} table-default{% endif %}">
                <td>
                  <a class="text-dark" href="{% url 'app1:agenda-events-day' event.date.year event.date.month event.date.day %}">{{ event.date|date:"d/m/Y" }}</a>
                </td>
                <td class="text-truncate">
                  <a class="text-dark" href="{% url 'app1:agenda-events-show' event.id %}">{{ event.event }}</a>
                </td>
              </tr>
            {% endfor %}
            </tbody>
          </table>
          {% with events as paginated %}
            {% include "app3/_layouts/pagination.html" %}
          {% endwith %}
          <hr/>
          <p>Você tem {{ total }} agendamento{{ total|pluralize }} registrado{{ total|pluralize }}.</p>
        {% else %}
          <div class="alert alert-secondary text-center">
            Sem agendamento cadastrado.
          </div>
        {% endif %}
        </div>
      </div>
    </main>
{% include "app3/agenda/modals/new.html" %}


{% endblock %}

app1/templates/app3/agenda/ops_400.html
{% extends "app3/_layouts/base.html" %}{% load static %}
{% block conteudo %}
    <main role="main">
      <div class="container py-5">
        <div class="col-12 col-md-6 offset-md-3 text-center">
          <img src="{% static 'app2/imgs/ops.png' %}" class="img-fluid" alt=""/>
          <br/>
          <h2>
            Erro 400<br/>
            <small>
              Requisição Ilegal!
            </small>
          </h2>
        </div>
      </div>
    </main>
{% endblock %}

app1/templates/app3/agenda/ops_500.html
{% extends "app3/_layouts/base.html" %}{% load static %}
{% block conteudo %}
    <main role="main">
      <div class="container py-5">
        <div class="col-12 col-md-6 offset-md-3 text-center">
          <img src="{% static 'app2/imgs/ops.png' %}" class="img-fluid" alt=""/>
          <br/>
          <h2>
            Erro 500<br/>
            <small>
              Erro interno!
            </small>
          </h2>
        </div>
      </div>
    </main>
{% endblock %}

app1/templates/app3/agenda/show.html
<!-- Comentarios de Serviços -->
{% extends "app3/_layouts/base.html" %}{% load static %}
{% block conteudo %}

    <main role="main">
      <div class="card">
        <div class="card-header d-flex justify-content-center">
          <div class="align-self-center text-center">
            <strong>
              {{ event.date|date:"l" }}
            </strong>
            <h1 class="display-4">
              {{ event.date.day }}
            </h1>
  	        {{ event.date|date:"d/m/Y" }}
          </div>
        </div>
        <div class="card-body">
          <div role="alert" class="d-flex alert {% if event.priority == '1' %} alert-success{% elif event.priority == '2' %} alert-warning{% elif event.priority == '3' %} alert-danger{% else %} alert-secondary{% endif %}">
            <div class="p-2 text-truncated">
              {{ event.event }}
            </div>
          </div>
        {% if comments|length > 0 %}
          <div class="container py-2">
          {% for comment in comments %}
            <div class="media mb-2">
              <img class="mr-3" src="{{ comment.avatar }}" alt="">
                <div class="media-body">
                  <blockquote class="blockquote">
                    &quot;{{ comment.text }}&quot;
                  </blockquote>
                  <footer class="blockquote-footer">
                    <strong>{{ comment.author }}</strong> | {{ comment.commented }}
                  </footer>
                </div>
              </div>
            {% endfor %}
            </div>
          {% else %}
            <div class="alert alert-secondary text-center">
              Não há comentários para este agendamento! Seja o primeiro a comentar!
            </div>
          {% endif %}
          <hr/>
          <div class="container">
            <form method="post" action="">
              {% csrf_token %}
              <input type="hidden" name="event" value="{{ event.id }}">
              <div class="form-group">
                <input type="text" class="form-control form-control-sm" id="addInputComment" name="text" placeholder="Escreva seu comentário" required>
              </div>
              <div class="form-row">
                <div class="col-auto">
                  <input type="text" class="form-control form-control-sm  mb-2" id="addInputAuthor" name="author" placeholder="Escreva seu nome" required>
                </div>
                <div class="col-auto">
                  <div class="input-group mb-2">
                    <input type="email" class="form-control form-control-sm" id="addInputMail" name="email" placeholder="Escreva seu e-mail" required>
                  </div>
                </div>
                <div class="col-auto mb-2">
                  <a href="{% url 'app1:agenda-events-all' %}" class="btn btn-sm btn-outline-danger mb-2">Voltar</a>
                  <button type="submit" class="btn btn-sm btn-primary mb-2">Enviar comentário</button>
                </div>
              </div>
                <hr/>
            </form>
              <hr/>
              <hr/>

          </div>
        </div>
      </div>
    </main>
{% endblock %}