app1/urls.py
from rest_framework import routers
from rest_framework.authtoken.views import obtain_auth_token

from app1.views import IndexFuncionarioTemplateView, FuncionarioListView, FuncionarioUpdateView, \
    FuncionarioDeleteView, IndexClienteTemplateView, ClienteCreateView, ClienteListView, ClienteUpdateView, \
    ClienteDeleteView, IndexFornecedorTemplateView, FornecedorCreateView, FornecedorListView, FornecedorUpdateView, \
    FornecedorDeleteView, IndexProdutoTemplateView, ProdutoCreateView, ProdutoListView, ProdutoUpdateView, \
    ProdutoDeleteView, ProdutoFuncionarioListView, IndexOrcamentoTemplateView, OrcamentoCreateView, \
    OrcamentoListView, OrcamentoUpdateView, OrcamentoDeleteView, IndexMetaTemplateView, MetaCreateView, MetaListView, \
    MetaUpdateView, MetaDeleteView
from django.urls import path, include

from . import views



router = routers.DefaultRouter()
router.register(r"events", views.EventViewSet)
router.register(r"comments", views.CommentViewSet)

app_name = 'app1'

urlpatterns = [
    path('login', views.loginn, name='login'),
    path('logout', views.logoutt, name='logout'),
    path('indexx', views.indexx, name='indexx'),
    path('manutencao', views.manutencao, name='manutencao'),
    path('funcionario/cadastrar/', views.funcionario, name="cadastra_funcionario"),
    path("api-token-auth/", obtain_auth_token, name="api_token_auth"),
    path("api/v1/", include(router.urls)),
    path("agenda", views.agenda, name="agenda-events"),
    path("all", views.all, name="agenda-events-all"),
    path("<int:id>", views.show, name="agenda-events-show"),
    path("<int:year>/<int:month>/<int:day>", views.day, name="agenda-events-day"),
    path("new", views.new, name="agenda-events-new"),
    path("delete/<int:id>", views.delete, name="agenda-events-delete"),
    path("edit", views.edit, name="agenda-events-edit"),



    # GET /
    path('principalfuncionario/', IndexFuncionarioTemplateView.as_view(), name="principalfuncionario"),

    # GET /funcionarios
    path('funcionarios/', FuncionarioListView.as_view(), name="lista_funcionarios"),

    # GET/POST /funcionario/{pk}
    path('funcionario/<pk>', FuncionarioUpdateView.as_view(), name="atualiza_funcionario"),

    # GET/POST /funcionarios/excluir/{pk}
    path('funcionario/excluir/<pk>', FuncionarioDeleteView.as_view(), name="deleta_funcionario"),

######################################################################################################

    # GET /
    path('principalcliente/', IndexClienteTemplateView.as_view(), name="principalcliente"),

    # GET /cliente/cadastrar
    path('cliente/cadastrar', ClienteCreateView.as_view(), name="cadastra_cliente"),

    # GET /clientes
    path('clientes/', ClienteListView.as_view(), name="lista_clientes"),

    # GET/POST /cliente/{pk}
    path('cliente/<pk>', ClienteUpdateView.as_view(), name="atualiza_cliente"),

    # GET/POST /cliente/excluir/{pk}
    path('cliente/excluir/<pk>', ClienteDeleteView.as_view(), name="deleta_cliente"),

######################################################################################################

    # GET /
    path('principal/fornecedor/', IndexFornecedorTemplateView.as_view(), name="principalfornecedor"),

    # GET /forncedor/cadastrar
    path('fornecedor/cadastrar', FornecedorCreateView.as_view(), name="cadastra_fornecedor"),

    # GET /fornecedores
    path('fornecedores/', FornecedorListView.as_view(), name="lista_fornecedores"),

    # GET/POST /fornecedor/{pk}
    path('fornecedor/<pk>', FornecedorUpdateView.as_view(), name="atualiza_fornecedor"),

    # GET/POST /fornecedor/excluir/{pk}
    path('fornecedor/excluir/<pk>', FornecedorDeleteView.as_view(), name="deleta_fornecedor"),

######################################################################################################

    # GET /
    path('principal/fornecedor/', IndexProdutoTemplateView.as_view(), name="principalproduto"),

    # GET /produto/cadastrar
    path('produto/cadastrar/', ProdutoCreateView.as_view(), name="cadastra_produto"),

    # GET /produtos
    path('produtos/', ProdutoListView.as_view(), name="lista_produtos"),

# GET /produtos
    path('produtos/funcionario/', ProdutoFuncionarioListView.as_view(), name="lista_produtos_funcionario"),

    # GET/POST /produto/{pk}
    path('produto/<pk>', ProdutoUpdateView.as_view(), name="atualiza_produto"),

    # GET/POST /produto/excluir/{pk}
    path('produto/excluir/<pk>', ProdutoDeleteView.as_view(), name="deleta_produto"),

######################################################################################################
######################################################################################################

    # GET /
    path('principal/orcamento/', IndexOrcamentoTemplateView.as_view(), name="principalorcamento"),

    # GET /orcamento/cadastrar
    path('orcamento/cadastrar/', OrcamentoCreateView.as_view(), name="cadastra_orcamento"),

    # GET /orcamentos
    path('orcamentos/', OrcamentoListView.as_view(), name="lista_orcamentos"),

    # GET/POST /orcamento/{pk}
    path('orcamento/<pk>', OrcamentoUpdateView.as_view(), name="atualiza_orcamento"),

    # GET/POST /orcamento/excluir/{pk}
    path('orcamento/excluir/<pk>', OrcamentoDeleteView.as_view(), name="deleta_orcamento"),

######################################################################################################

######################################################################################################

    # GET /
    path('principal/meta/', IndexMetaTemplateView.as_view(), name="principalmeta"),

    # GET /meta/cadastrar
    path('meta/cadastrar/', MetaCreateView.as_view(), name="cadastra_meta"),

    # GET /metas
    path('metas/', MetaListView.as_view(), name="lista_metas"),

    # GET/POST /meta/{pk}
    path('meta/<pk>', MetaUpdateView.as_view(), name="atualiza_meta"),

    # GET/POST /meta/excluir/{pk}
    path('meta/excluir/<pk>', MetaDeleteView.as_view(), name="deleta_meta"),


]

security/urls.py
from django.contrib import admin
from django.urls.conf import include
from django.urls import path
from app1 import views


urlpatterns = [
    path('', views.loginn, name="login"),
    path('app1/', include('app1.urls')),
    path('admin/', admin.site.urls, name="admin"),
]

app1/views.py
from datetime import datetime, timedelta

from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from django.core.paginator import Paginator, InvalidPage
from django.http import HttpResponseRedirect, HttpResponse
from django.shortcuts import get_object_or_404, redirect, render
from django.urls import reverse
from django.urls import reverse_lazy
from django.utils.timezone import localdate
from django.views.defaults import bad_request, server_error
from django.views.generic import TemplateView, ListView, UpdateView, CreateView, DeleteView
from rest_framework import filters, viewsets
from rest_framework.permissions import IsAuthenticated


from app1.forms import FormCliente, FormFuncionario, FormFornecedor, FormProduto, EventForm, CommentForm, FormOrcamento, \
    FormMeta
from app1.models import Funcionario, Cliente, Fornecedor, Produto, Event, Comment, Orcamento, Metas
from .serializers import CommentSerializer, EventSerializer
from .services import split_str_date

ITEMS_PER_PAGE = 5
FIRST_PAGE = 1


# PÁGINA PRINCIPAL INDEX
# ----------------------------------------------
def indexx(request):
    return render(request, 'app3/index.html')

# PÁGINA PRINCIPAL MANUTENÇÃO
# ----------------------------------------------
def manutencao(request):
    return render(request, 'app3/manutencao.html')

# PÁGINA PRINCIPAL LOGIN
# ----------------------------------------------
def loginn(request):
    if request.method == 'POST':
        usuario = request.POST.get('usuario')
        senha = request.POST.get('senha')
        user = authenticate(username=usuario, password=senha)

        if user:
            if user.is_active:
                login(request, user)
                return HttpResponseRedirect(reverse('app1:indexx'))
            else:
                return HttpResponse("Sua Conta Não Esta Ativa.")
        else:
            print("Alguém Tentou Fazer Login e Falhou")
            print("Foi Usado userName: {} e senha: {}".format(usuario, senha))
            return HttpResponse("O Login ou Senha Está Incorreto.")

    else:
        return render(request, 'app3/login.html', {})

# PÁGINA PRINCIPAL LOGOUT
# ----------------------------------------------
@login_required
def logoutt(request):
    logout(request)
    return HttpResponseRedirect(reverse('login'))

# PÁGINA CADASTRO FUNCIONARIO
# ----------------------------------------------
def funcionario(request):
    if request.method == 'POST':
        form = FormFuncionario(request.POST)
        if form.is_valid():
            usuario = User()
            usuario.first_name = form.cleaned_data['first_name']
            usuario.last_name = form.cleaned_data['last_name']
            usuario.email = form.cleaned_data['email']
            usuario.username = form.cleaned_data['username']
            usuario.password = form.cleaned_data['password']

            usuario.save()
            usuario.set_password(usuario.password)
            usuario.save()

            func = Funcionario()
            func.CPF = form.cleaned_data['CPF']
            func.nascimento = form.cleaned_data['nascimento']
            func.telefone = form.cleaned_data['telefone']
            func.endereco = form.cleaned_data['endereco']
            func.CTPS = form.cleaned_data['CTPS']
            func.cargo = form.cleaned_data['cargo']

            func.usuario = usuario
            func.save()
            return HttpResponseRedirect(reverse('app1:lista_funcionarios'))
    else:
        form = FormFuncionario()

    return render(request, 'app3/funcionario/cadastra.html', {'form': form,})

# PÁGINA PRINCIPAL FUNCIONARIO
# ----------------------------------------------

class IndexFuncionarioTemplateView(TemplateView):
    template_name = "app3/funcionario/principal.html"

# LISTA DE FUNCIONÁRIOS
# ----------------------------------------------

class FuncionarioListView(ListView):
    template_name = "app3/funcionario/lista.html"
    model = Funcionario
    context_object_name = "funcionarios"


# ATUALIZAÇÃO DE FUNCIONÁRIOS
# ----------------------------------------------

class FuncionarioUpdateView(UpdateView):
    template_name = "app3/funcionario/atualiza.html"
    model = Funcionario
    fields = '__all__'
    context_object_name = 'funcionario'
    success_url = reverse_lazy("app1:lista_funcionarios")


# EXCLUSÃO DE FUNCIONÁRIOS
# ----------------------------------------------

class FuncionarioDeleteView(DeleteView):
    template_name = "app3/funcionario/exclui.html"
    model = Funcionario
    context_object_name = 'funcionario'
    success_url = reverse_lazy("app1:lista_funcionarios")

##################################################################################

# PÁGINA PRINCIPAL CLIENTE
# ----------------------------------------------

class IndexClienteTemplateView(TemplateView):
    template_name = "app3/cliente/principal.html"

# LISTA DE CLIENTE
# ----------------------------------------------

class ClienteListView(ListView):
    template_name = "app3/cliente/lista.html"
    model = Cliente
    context_object_name = "clientes"

# CADASTRAMENTO DE CLIENTE
# ----------------------------------------------

class ClienteCreateView(CreateView):
    template_name = "app3/cliente/cadastra.html"
    model = Cliente
    form_class = FormCliente
    success_url = reverse_lazy("app1:lista_clientes")

# ATUALIZAÇÃO DE CLIENTE
# ----------------------------------------------

class ClienteUpdateView(UpdateView):
    template_name = "app3/cliente/atualiza.html"
    model = Cliente
    fields = '__all__'
    context_object_name = 'cliente'
    success_url = reverse_lazy("app1:lista_clientes")


# EXCLUSÃO DE CLIENTE
# ----------------------------------------------

class ClienteDeleteView(DeleteView):
    template_name = "app3/cliente/exclui.html"
    model = Cliente
    context_object_name = 'cliente'
    success_url = reverse_lazy("app1:lista_clientes")

##################################################################################

# PÁGINA PRINCIPAL FORNECEDOR
# ----------------------------------------------

class IndexFornecedorTemplateView(TemplateView):
    template_name = "app3/fornecedor/principal.html"

# LISTA DE FORNECEDOR
# ----------------------------------------------

class FornecedorListView(ListView):
    template_name = "app3/fornecedor/lista.html"
    model = Fornecedor
    context_object_name = "fornecedores"

# CADASTRAMENTO DE FORNECEDOR
# ----------------------------------------------

class FornecedorCreateView(CreateView):
    template_name = "app3/fornecedor/cadastra.html"
    model = Fornecedor
    form_class = FormFornecedor
    success_url = reverse_lazy("app1:lista_fornecedores")

# ATUALIZAÇÃO DE FORNECEDOR
# ----------------------------------------------

class FornecedorUpdateView(UpdateView):
    template_name = "app3/fornecedor/atualiza.html"
    model = Fornecedor
    fields = '__all__'
    context_object_name = 'fornecedor'
    success_url = reverse_lazy("app1:lista_fornecedores")


# EXCLUSÃO DE FORNECEDOR
# ----------------------------------------------

class FornecedorDeleteView(DeleteView):
    template_name = "app3/fornecedor/exclui.html"
    model = Fornecedor
    context_object_name = 'fornecedor'
    success_url = reverse_lazy("app1:lista_fornecedores")

##################################################################################

# LISTA DE PRODUTO
# ----------------------------------------------

class ProdutoFuncionarioListView(ListView):
    template_name = "app3/produto/listafuncionario.html"
    model = Produto
    context_object_name = "produtos"

# PÁGINA PRINCIPAL PRODUTO
# ----------------------------------------------

class IndexProdutoTemplateView(TemplateView):
    template_name = "app3/fornecedor/principal.html"

# LISTA DE PRODUTO
# ----------------------------------------------

class ProdutoListView(ListView):
    template_name = "app3/produto/lista.html"
    model = Produto
    context_object_name = "produtos"

# CADASTRAMENTO DE PRODUTO
# ----------------------------------------------

class ProdutoCreateView(CreateView):
    template_name = "app3/produto/cadastra.html"
    model = Produto
    form_class = FormProduto
    success_url = reverse_lazy("app1:lista_produtos")

# ATUALIZAÇÃO DE PRODUTO
# ----------------------------------------------

class ProdutoUpdateView(UpdateView):
    template_name = "app3/produto/atualiza.html"
    model = Produto
    fields = '__all__'
    context_object_name = 'produto'
    success_url = reverse_lazy("app1:lista_produtos")


# EXCLUSÃO DE PRODUTO
# ----------------------------------------------

class ProdutoDeleteView(DeleteView):
    template_name = "app3/produto/exclui.html"
    model = Produto
    context_object_name = 'produto'
    success_url = reverse_lazy("app1:lista_produtos")

##################################################################################

# Create your views here.
class EventViewSet(viewsets.ModelViewSet):
    """
    Disponibiliza os eventos da agenda como uma API REST.
    """

    queryset = Event.objects.all()
    serializer_class = EventSerializer

    permission_classes = (IsAuthenticated,)


class CommentViewSet(viewsets.ModelViewSet):
    """
    Disponibiliza os eventos da agenda como uma API REST.
    """

    queryset = Comment.objects.all()
    serializer_class = CommentSerializer
    filter_backends = (filters.SearchFilter,)
    search_fields = ("event__id",)

    permission_classes = (IsAuthenticated,)

# PÁGINA PRINCIPAL AGENDA
# ----------------------------------------------
@login_required
def agenda(request):
    """
    Exibe a página principal da aplicaão.
    """
    context = {
        "hide_new_button": True,
        "priorities": Event.priorities_list,
        "today": localdate(),
    }

    return render(request, "app3/agenda/agenda.html", context)


@login_required
def all(request):
    """

app1/templates/app3/meta/atualiza.html
{% extends "app3/_layouts/base.html" %}

{% load widget_tweaks %}

{% block title %}Atualização de Metas{% endblock %}

{% block conteudo %}
<div class="container mt-1 mb-5">
  <div class="row">
    <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
      <div class="card">
        <div class="card-body">
          <h5 class="card-title">Atualizar Metas</h5>
          <form enctype="multipart/form-data" method="post">
            <!-- Não se esqueça dessa tag -->
            {% csrf_token %}

                                           <!-- Cargo -->
                    <div class="input-group mb-3">
                         <div class="input-group-prepend">
                               <span class="input-group-text">Cargo</span>
                         </div>
                            {% render_field form.cargo class+="form-control" %}
                    </div>
                                        <!-- Mês de Referência -->
                    <div class="input-group mb-3">
                         <div class="input-group-prepend">
                               <span class="input-group-text">Mês de Referência</span>
                         </div>
                            {% render_field form.meses class+="form-control" %}
                    </div>
                                       <!-- Data -->
                    <div class="input-group mb-3">
                         <div class="input-group-prepend">
                               <span class="input-group-text">Data da Criação/Modificação</span>
                         </div>
                            {% render_field form.data class+="form-control" %}
                    </div>

                                        <!-- Meta -->
                    <div class="input-group mb-3">
                         <div class="input-group-prepend">
                               <span class="input-group-text">Meta</span>
                         </div>
                            {% render_field form.meta class+="form-control" %}
                    </div>
                                          <!-- Meta Concluida -->
                    <div class="input-group mb-3">
                         <div class="input-group-prepend">
                               <span class="input-group-text">Concluída</span>
                         </div>
                            {% render_field form.concluida class+="form-control" %}
                    </div>
            <hr/>
            <div class="text-right">
              <a href="{% url 'app1:lista_metas' %}" class="btn btn-outline-danger">Voltar</a>
              <button class="btn btn-success">Enviar</button>
            </div>
              <hr>
          </form>
        </div>
      </div>
    </div>
  </div>
</div>
{% endblock %}

app1/templates/app3/meta/cadastra.html
<!DOCTYPE html>
{% extends "app3/_layouts/base.html" %}

{% load widget_tweaks %}
{% load static %}
{% block title %}Cadastro de Meta{% endblock %}

{% block conteudo %}
     <div class="container mt-1 mb-5">
       <div class="row">
         <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
           <div class="card">
             <div class="card-body">
                <h5 class="card-title">Cadastro de Metas</h5>
                <p class="card-text">Complete o formulário abaixo para cadastrar uma nova <code>Meta.</code></p>

                <form enctype="multipart/form-data" method="POST">
                    {% csrf_token %}

                                           <!-- Cargo -->
                    <div class="input-group mb-3">
                         <div class="input-group-prepend">
                               <span class="input-group-text">Cargo</span>
                         </div>
                            {% render_field form.cargo class+="form-control" %}
                    </div>
                                        <!-- Mês de Referência -->
                    <div class="input-group mb-3">
                         <div class="input-group-prepend">
                               <span class="input-group-text">Mês de Referência</span>
                         </div>
                            {% render_field form.meses class+="form-control" %}
                    </div>
                                       <!-- Data -->
                    <div class="input-group mb-3">
                         <div class="input-group-prepend">
                               <span class="input-group-text">Data da Criação/Modificação</span>
                         </div>
                            {% render_field form.data class+="form-control" %}
                    </div>

                                        <!-- Meta -->
                    <div class="input-group mb-3">
                         <div class="input-group-prepend">
                               <span class="input-group-text">Meta</span>
                         </div>
                            {% render_field form.meta class+="form-control" %}
                    </div>
                                     <!-- Meta Concluida -->
                    <div class="input-group mb-3">
                         <div class="input-group-prepend">
                               <span class="input-group-text">Concluída</span>
                         </div>
                             {% render_field form.concluida class+="form-control form-inline" %}
                    </div>
                       <hr>
                            <div class="text-right">
                                <a href="{% url 'app1:lista_metas' %}" class="btn btn-outline-danger">Voltar</a>
                                <button class="btn btn-success">Enviar</button>
                            </div>
                    <hr>
                </form>
             </div>
           </div>
         </div>
       </div>
     </div>
{% endblock %}

app1/templates/app3/meta/exclui.html
<!-- Estendemos do template base -->
{% extends "app3/_layouts/base.html" %}

<!-- Bloco que define o <title></title> da nossa página -->
{% block title %}Exlusão de Meta{% endblock %}

<!-- Bloco de conteúdo da nossa página -->
{% block conteudo %}
  <div class="container mt-5">
    <div class="card">
      <div class="card-body">
        <h5 class="card-title">Exclusão de Metas</h5>

        <p class="card-text">
          Você tem certeza que quer excluir a meta <b>{{ meta.meta }}</b>?
        </p>

        <form method="post">
          {% csrf_token %}

          <hr />
          <div class="text-right">
            <a href="{% url 'app1:lista_metas' %}" class="btn btn-outline-danger">
              Cancelar
            </a>
            <button class="btn btn-danger">Excluir</button>
          </div>
        </form>
      </div>
    </div>
  </div>
{% endblock %}

app1/templates/app3/meta/lista.html
{% extends "app3/_layouts/base.html" %}

{% block title %}Metas{% endblock %}

{% block conteudo %}

<div class="container-fluid mt-2 mb-5">
  <div class="row">
    <div class="col-lg-15 col-md-12 col-sm-12 col-xs-12">
      <div class="card">
        <div class="card-body">
          <h5 class="card-title">Lista de Metas</h5>

          {% if metas|length > 0 %}
            <p class="card-text">
              Aqui está a lista de <code>Metas</code> cadastrados.
            </p>
            <div class="search-list">
            <table class="table" id="myTable">
              <thead class="thead-dark">
              <tr class="text-center">
                <th scope="col">Id</th>
                <th scope="col">Cargo</th>
                <th scope="col">Data Criação/Modificação</th>
                <th scope="col">Mês de Referência</th>
                <th scope="col">Meta</th>
                <th scope="col">Concluída</th>
                  {% if user.is_staff %}
                      <th scope="col" class="text-center">Ações</th>
                  {% else %}
                      <th scope="col" class="text-center">----</th>
                  {% endif %}
              </tr>
              </thead>
              <tbody>
              {% for meta in metas %}
                <tr class="text-center">
                  <th scope="row">{{ meta.id }}</th>
                  <td>{{ meta.cargo }}</td>
                  <td>{{ meta.data|date:"d/m/o" }}</td>
                  <td>{{ meta.meses }}</td>
                  <td>{{ meta.meta }}</td>
                  <td>{{ meta.concluida }}</td>


                      {% if user.is_staff %}
                         <td class="text-center">
                              <a href="{% url 'app1:atualiza_meta' pk=meta.id %}" class="btn btn-primary">Atualizar</a>
                              <a href="{% url 'app1:deleta_meta' pk=meta.id %}" class="btn btn-danger">Excluir</a>
                      {% else %}
                              <th scope="col" class="text-center">----</th>
                         </td>
                      {% endif %}

                </tr>
              {% endfor %}
              </tbody>
            </table>
            </div>
        {% else %}
          <div class="text-center mt-5 mb-5 jumbotron">
            <h5>Nenhuma <code>Meta</code> cadastrado ainda.</h5>
          </div>
        {% endif %}
          <hr />
        {% if user.is_staff %}
          <div class="text-right">
            <a href="{% url 'app1:cadastra_meta' %}" class="btn btn-success">
              Cadastrar Meta
            </a>
          </div>
        {% endif %}
        <hr>
        </div>
      </div>
    </div>
  </div>
</div>
{% endblock %}

app1/templates/app3/meta/principal.html
<!-- Estendemos do template base -->
{% extends "app3/_layouts/base.html" %}

<!-- Bloco que define o <title></title> da nossa página -->
{% block title %}Meta{% endblock %}

<!-- Bloco de conteúdo da nossa página -->
{% block conteudo %}
<div class="container mt-5">
  <div class="row">
      {% if user.is_staff %}
    <div class="col-lg-6 col-md-6 col-sm-6 col-xs-12">
      <div class="card">
        <div class="card-body">
          <h5 class="card-title">Cadastrar Meta</h5>
          <p class="card-text">
            Cadastre aqui um novo <code>Meta</code>.
          </p>
          <a href="{% url 'app1:cadastra_meta' %}" class="btn btn-success">Nova Meta</a>
        </div>
      </div>
    </div>
      {% endif %}
    <div class="col-lg-6 col-md-6 col-sm-6 col-xs-12">
      <div class="card">
        <div class="card-body">
          <h5 class="card-title">Lista de Metas</h5>
          <p class="card-text">
            Veja aqui a lista de <code>Metas</code> cadastrados.
          </p>
          <a href="{% url 'app1:lista_metas' %}" class="btn btn-primary">Vá para Lista</a>
        </div>
      </div>
    </div>
  </div>
</div>
{% endblock %}